<a href="https://colab.research.google.com/github/deepikagoel1/Edufabrica-aiml/blob/main/23_June_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b = np.array([1, 2, 0, 0, 4, 0])
a = np.nonzero(b)

In [ ]:
b

array([1, 2, 0, 0, 4, 0])

In [ ]:
a

(array([0, 1, 4]),)

In [ ]:
b[[0 ,1, 4]]

array([1, 2, 4])

In [ ]:
x =  np.random.random(30)
x

array([0.59980164, 0.73090837, 0.87488159, 0.5596454 , 0.00901225,
       0.58742981, 0.61615648, 0.27199062, 0.02814152, 0.73830244,
       0.96752012, 0.0425118 , 0.93102714, 0.98968224, 0.63673413,
       0.53470849, 0.9878008 , 0.0352646 , 0.92286136, 0.40227153,
       0.85470573, 0.57251015, 0.03503852, 0.29457975, 0.20438801,
       0.54205102, 0.35525051, 0.82089872, 0.11478294, 0.550363  ])

In [ ]:
x.mean()

0.5270406888867716

In [ ]:
a = np.zeros((8,8), dtype = 'int')

In [ ]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a[1::2, ::2] = 1

In [ ]:
a[::2, 1::2 ] = 1

In [ ]:
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.diag(np.arange(1,5), k= -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
x = np.random.random((5, 5))
x

array([[0.65111967, 0.12566455, 0.69669637, 0.73007169, 0.11525562],
       [0.27877736, 0.80586735, 0.53246386, 0.25967855, 0.39717585],
       [0.12148452, 0.41923704, 0.47732693, 0.30385366, 0.22698909],
       [0.67042662, 0.96530559, 0.25285677, 0.16531293, 0.44167534],
       [0.60211191, 0.37004441, 0.57303465, 0.55134697, 0.11582709]])

$Normalise = \frac{x - xmin}{xmax - xmin}$

In [ ]:
xmax, xmin = x.max(), x.min()

In [ ]:
N = (x - xmin)/(xmax - xmin)

In [ ]:
print(N)

[[6.30391236e-01 1.22450784e-02 6.84007734e-01 7.23270500e-01
  0.00000000e+00]
 [1.92367209e-01 8.12436630e-01 4.90804370e-01 1.69899339e-01
  3.31651359e-01]
 [7.32768940e-03 3.57604183e-01 4.25941203e-01 2.21867004e-01
  1.31443415e-01]
 [6.53103962e-01 1.00000000e+00 1.61874191e-01 5.88874934e-02
  3.84000624e-01]
 [5.72738441e-01 2.99733901e-01 5.38531910e-01 5.13018495e-01
  6.72282443e-04]]


In [ ]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [ ]:
np.unravel_index([22, 41, 37], (8, 7))

(array([3, 5, 5]), array([1, 6, 2]))

In [ ]:
x

array([[0.65111967, 0.12566455, 0.69669637, 0.73007169, 0.11525562],
       [0.27877736, 0.80586735, 0.53246386, 0.25967855, 0.39717585],
       [0.12148452, 0.41923704, 0.47732693, 0.30385366, 0.22698909],
       [0.67042662, 0.96530559, 0.25285677, 0.16531293, 0.44167534],
       [0.60211191, 0.37004441, 0.57303465, 0.55134697, 0.11582709]])

In [ ]:
x[0][1]

0.1256645486763487

In [ ]:
x[0,1]

0.1256645486763487

In [ ]:
string = 'abcdefghijklmnop'

**create an array consistiing of 100 rows and 10 cols filled with string values in combinations of 3**<br>
Ex = 'abc', 'ade', 'klm'

In [ ]:
import random 
cs = []
for i in np.arange(20):
    val = ''.join(random.sample(string,3))
    if val in cs:
        continue
    else:
        cs.append(val)

In [ ]:
cs.sort()
np.array(cs).reshape(5,4)

array([['afe', 'bde', 'bdh', 'bhi'],
       ['bih', 'bij', 'caj', 'che'],
       ['fhe', 'gef', 'gfj', 'haf'],
       ['hcg', 'hjg', 'iba', 'idh'],
       ['igh', 'ijf', 'jhc', 'jhg']], dtype='<U3')

In [ ]:
np.where(cs == 'bed')

(array([75]), array([3]))

In [ ]:
cs[75,3]

'bed'

In [ ]:
cs[75]

array(['jbg', 'dbh', 'gaj', 'bed', 'igb', 'dji', 'jic', 'dje', 'ief',
       'jgh'], dtype='<U3')

In [ ]:
g_code = []
for i in np.arange(10000):
    code = 'G-' + ''.join(random.sample('0123456789',6))
    g_code.append(code)
codes = np.array(g_code).reshape(1000, 10)

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(codes)[:10]

In [ ]:
df

0         1         2         3         4         5         6  \
0  G-712460  G-704361  G-679340  G-860723  G-854190  G-153762  G-083649   
1  G-943017  G-069547  G-134650  G-243569  G-120347  G-763084  G-319764   
2  G-796824  G-312794  G-087465  G-126854  G-169207  G-206793  G-302964   
3  G-758230  G-148362  G-896217  G-537814  G-963514  G-619507  G-801752   
4  G-032765  G-401932  G-285147  G-907684  G-603721  G-190638  G-154892   
5  G-618527  G-164503  G-716390  G-375419  G-463792  G-421809  G-748093   
6  G-718249  G-297348  G-923017  G-270439  G-671428  G-912053  G-765038   
7  G-127453  G-389276  G-543102  G-319064  G-415396  G-958241  G-015928   
8  G-918206  G-468791  G-085937  G-915873  G-574863  G-712693  G-645913   
9  G-965174  G-749610  G-092586  G-760891  G-062937  G-457321  G-508174   

          7         8         9  
0  G-075319  G-593482  G-287305  
1  G-632401  G-653807  G-632947  
2  G-412970  G-273518  G-368029  
3  G-194358  G-182503  G-298753  
4  G-407586  G-450732  G-794632  
5  G-174805  G-346015  G-463590  
6  G-791306  G-361279  G-952043  
7  G-035817  G-467935  G-609381  
8  G-869570  G-985172  G-356809  
9  G-874092  G-945271  G-067259

In [ ]:
a,b,c = np.unique(codes, return_index= True, return_counts= True)

In [ ]:
a[:50]

array(['G-012368', 'G-012379', 'G-012385', 'G-012653', 'G-012675',
       'G-012685', 'G-012695', 'G-012845', 'G-012849', 'G-012935',
       'G-012943', 'G-012968', 'G-012986', 'G-013284', 'G-013294',
       'G-013296', 'G-013465', 'G-013546', 'G-013574', 'G-013578',
       'G-013598', 'G-013629', 'G-013645', 'G-013726', 'G-013729',
       'G-013764', 'G-013768', 'G-013845', 'G-013852', 'G-013857',
       'G-013862', 'G-013865', 'G-013985', 'G-014239', 'G-014253',
       'G-014259', 'G-014327', 'G-014365', 'G-014368', 'G-014598',
       'G-014628', 'G-014698', 'G-014765', 'G-014769', 'G-014786',
       'G-014857', 'G-014926', 'G-014986', 'G-015246', 'G-015274'],
      dtype='<U8')

In [ ]:
b[:50]

array([5411,  570, 8245, 9755,  443, 6565, 3376, 5905, 2723, 6149, 4258,
       5376, 9480, 6754, 6887, 6671, 2262, 3062, 9167, 1113, 7848, 8244,
       6756, 9897, 5207, 6252, 7581, 8072, 7540, 4621, 8158, 4824, 4903,
       9535, 1326, 4077, 2825, 5825, 6523, 3075, 5819, 7412, 1161,  784,
       9836, 2497, 4612, 8699, 7831,  847])

In [ ]:
c[:50]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2])

In [ ]:
a[5058]

'G-520367'

In [ ]:
np.where(codes =='G-015274' )

(array([ 84, 235]), array([7, 8]))

In [ ]:
codes[[84, 235],[7, 8]]

array(['G-015274', 'G-015274'], dtype='<U8')

In [ ]:
a[49]

'G-015274'

In [ ]:
np.where(c>1)

(array([  30,   49,   96,  126,  155,  164,  188,  207,  241,  243,  245,
         275,  295,  296,  316,  350,  372,  425,  479,  484,  498,  528,
         539,  544,  590,  597,  701,  756,  777,  889,  910,  983,  994,
        1004, 1027, 1045, 1055, 1067, 1084, 1177, 1214, 1215, 1269, 1325,
        1326, 1377, 1379, 1381, 1451, 1469, 1478, 1502, 1523, 1538, 1544,
        1559, 1581, 1617, 1642, 1645, 1667, 1687, 1691, 1693, 1712, 1718,
        1827, 1830, 1831, 1834, 1869, 1919, 1929, 1942, 1945, 1954, 1988,
        1993, 1996, 2134, 2138, 2151, 2191, 2202, 2209, 2240, 2250, 2278,
        2282, 2290, 2297, 2318, 2334, 2346, 2377, 2379, 2421, 2437, 2474,
        2521, 2590, 2644, 2686, 2721, 2798, 2803, 2806, 2822, 2826, 2872,
        2891, 2913, 2939, 2941, 2991, 3052, 3069, 3093, 3154, 3223, 3276,
        3283, 3288, 3336, 3360, 3375, 3376, 3382, 3412, 3421, 3483, 3496,
        3524, 3536, 3593, 3604, 3625, 3632, 3633, 3657, 3705, 3716, 3718,
        3729, 3743, 3932, 3969, 3980, 

In [ ]:
np.tile([3],5)

array([3, 3, 3, 3, 3])

In [ ]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
a = np.arange(9)
a[(a<6) & (a>2)] *= -1
a

array([ 0,  1,  2, -3, -4, -5,  6,  7,  8])

In [ ]:
a[3:6]

array([-3, -4, -5])

In [ ]:
a[-2:]*= -2

In [ ]:
a

array([  0,   1,   2,  -3,  -4,  -5,   6, -14, -16])

In [ ]:
a[a>3]

array([6])

In [ ]:
np.tile([1, 2], 5)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [ ]:
np.tile(3, 5)

array([3, 3, 3, 3, 3])