<a href="https://colab.research.google.com/github/deepikagoel1/Edufabrica-aiml/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = 'https://www.freecodecamp.org/news/content/images/2020/07/numpy.png' width="300"/>

#  What is NumPy ?

NumPy stands for Numerical Python and is the core library for numeric and Scientific computing.It provides a high - performance multidimensional array object, and tools for working with these arrays.

## Where is NumPy used ?
Python NumPy Arrays provide tools for c , c ++ , etc. It is also used in the linear algebra, random no. capability

## What is NumPy Array ?¶
Np Array is a powerful N - dimensional Array object which is in the form of rows and columns.The most important object tht you define in numpy is N- dimensional Arrays is called as Ndarray. This describes the collection of items of the same dtype.

## Dtype

Every item in an ndarray takes the same size of block in the memory, each of them ahs a particuar data type that is called as dtype.

# Importing the Package and checking its <font color = 'green'>Version</font>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.20.1'

## Creating an NumPy Array

In [ ]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
arr2d = np.array([[1, 2, 3] , [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr0d = np.array(23)
arr0d

array(23)

# Inspection of Arrays
shape, len , ndim, ndmin, size, dtype, itemsize, astype, dtype.name

## `ndim` 


Returns Number of array dimensions

In [ ]:
arr.ndim

1

In [ ]:
arr2d.ndim

2

## `len`

Returns the length of the array

In [ ]:
len(arr)

3

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
len(arr2d)

2

## `size` 

Return the Number of array elements.

In [ ]:
arr2d.size

6

In [ ]:
arr.size

3

## `shape` 

Returns the number of dimensions of the array in tuples(rows, cols)

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## `dtype`

Returns the data types of the array

In [ ]:
np.array([1, 2.3])

array([1. , 2.3])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
[1, 2.3, 3j]

[1, 2.3, 3j]

## `dtype.name`

Returns the data type name of the array 

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr.dtype.name

'int64'

In [ ]:
np.array([True, False]).dtype.name

'bool'

In [ ]:
np.array([23j, -5j]).dtype.name

'complex128'

## `ndmin` 

define the no of dimensions of your array

In [ ]:
arr

array([1, 2, 3])

In [ ]:
np.array(arr2d, ndmin = 4)

array([[[[1, 2, 3],
         [4, 5, 6]]]])

## `astype` 

In [ ]:
np.array([True, False]).astype('int')

array([1, 0])

In [ ]:
arr.astype('float')

array([1., 2., 3.])

# Array mathematics

add, subtract, multiply, divide, sqrt, log, sin, cos, dot

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [ ]:
a,b

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]))

## `add`

performs addition on the array 

In [ ]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

## `subtraction`

performs the subtraction of the array

In [ ]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
a - b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

## `multiply`

multiply the array 

In [ ]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

## `divide`

divide the array

In [ ]:
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

## `exp` $e^{array}$

find the exponentiation of array [e to the power of individual elements of array]

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.e

2.718281828459045

In [ ]:
a

array([1, 2, 3])

## `sin`

Returns the sine values of array

In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

## `cos`

Returns the cos values of array

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## `log`

Returns the log vaues of array


In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

## `dot` 

Returns the dot product of the Matrix / Array.

a = [A1, B1, C1]<br>
b = [A2, B2, C2]

dot = [A1* A2 + B1 * B2 + C1 * C2] = [A1A2 + B1B2 + C1C2]

In [ ]:
c = np.array([4, 2, -3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
c

array([4, 5, 6])

In [ ]:
np.dot(a,c)

32

In [ ]:
1 * 4 + 2 * 5 + 3 * 6

32

# Comparing Arrays

`Element Wise Comparison`

In [ ]:
a

array([1, 2, 3])

In [ ]:
c

array([ 4,  2, -3])

In [ ]:
a == c

array([False,  True, False])

In [ ]:
a < c

array([ True, False, False])

In [ ]:
a >= c

array([False,  True,  True])

`Array wise Comparison`

In [ ]:
np.array_equal(a,b)

False

In [ ]:
np.append(a, c)

array([ 1,  2,  3,  4,  2, -3])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[0][0] = 20

In [ ]:
arr2d

array([[20,  2,  3],
       [ 4,  5,  6]])