<a href="https://colab.research.google.com/github/deepikagoel1/Edufabrica-aiml/blob/main/NumPy_Excersie_I_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Excercise - NumPy I </center>

### 1. Import the Package under the name np

In [1]:
import numpy as np

### 2. Print the NumPy version

In [2]:
np.__version__

'1.19.5'

### 3. Create a 2d Array

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

### 4. Create an Array and find the sqrt, and sin vaules of it

In [4]:
np.sqrt(arr2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [5]:
np.sin(arr2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

### 5. Create a 6d Array using ndmin and convert it to Bool Type

In [7]:
arr6d = np.array(arr2d, ndmin = 6)
arr6d

array([[[[[[1, 2, 3],
           [4, 5, 6]]]]]])

In [12]:
np.all(arr6d)

True

### 6. Given the array below, find the dot product of it

In [13]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 4, 5])

### 7. Check if All the elements of `arr1` is greater than `arr2`

In [14]:
arr3 = np.dot(arr1, arr2)
arr3

38

### 8. given below is an array find the number of rows of the array and the total number of elements

In [15]:
arr3 = np.array([[1, 2], [2, 3], [3, 4], [5, 6]])

In [16]:
arr3.shape[0]

4

In [17]:
arr3.size

8

### 9. Create a 3d Array and find its shape

In [19]:
arr4 = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])
arr4

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [20]:
arr4.ndim

3

### 10. Compare whether arr1 and arr2 are equal ? 

In [21]:
arr1 == arr2

array([False, False, False])